import assert from "node:assert/strict";
import { test } from "node:test";
import * as fa3 from "../../dist/documents/fa3.js";

const REQUIRED_TS_FA3_SYMBOLS = [
  "Address",
  "AdvanceCorrectionInvoiceBuilder",
  "AdvanceInvoiceBuilder",
  "AdvancePayment",
  "BankAccount",
  "BaseFA3Builder",
  "BasicInvoiceBuilder",
  "CorrectionInvoiceBuilder",
  "CorrectionType",
  "CoverageStatus",
  "FA3BatchDraft",
  "FA3Draft",
  "FA3Importer",
  "FA3Invoice",
  "FA3InvoiceBuilder",
  "FA3InvoiceKind",
  "FA3Line",
  "FA3Party",
  "FA3Template",
  "FA3ValidationIssue",
  "FA3XmlValidationError",
  "GTUCode",
  "ImportMode",
  "InvoiceLine",
  "InvoiceParty",
  "Order",
  "PartialPayment",
  "PartyIdentifier",
  "PartyIdentifierKind",
  "PaymentMethod",
  "PaymentTerms",
  "RawXmlExtension",
  "Settlement",
  "SettlementAdjustment",
  "SettlementCorrectionInvoiceBuilder",
  "SettlementInvoiceBuilder",
  "SimplifiedInvoiceBuilder",
  "TaxCategory",
  "ThirdPartyRole",
  "TransportKind",
  "XsdCoverageEntry",
  "XsdCoverageReport",
  "XsdElement",
  "auditFa3XsdCoverage",
  "audit_fa3_xsd_coverage",
  "invoiceToXml",
  "invoice_to_xml",
  "loadFa3SchemaWithLocalImports",
  "parseFa3XsdElements",
  "parse_fa3_xsd_elements",
  "resolveFa3SchemaEntryPath",
  "toBatchDraft",
  "validateFa3Xml",
  "validateFa3XmlXsd",
  "validate_fa3_xml_xsd",
];

const ACCEPTED_TS_FA3_SYMBOLS = new Set([
  ...REQUIRED_TS_FA3_SYMBOLS,
  "AdditionalDescription",
  "Annotation",
  "AnnotationSet",
  "Attachment",
  "AttachmentBlock",
  "AttachmentTable",
  "AuthorizedPartyRole",
  "Contact",
  "Contract",
  "CorrectedAdvanceState",
  "CorrectionReference",
  "Discount",
  "ExciseRefund",
  "FA3_FORM_VARIANT",
  "FA3ImportError",
  "FA3ImportResult",
  "FA3InvalidRow",
  "FA3ValidationResult",
  "Footer",
  "loadLibxml",
  "sanitizeFileName",
  "validateAndReturnXml",
  "LineIdentifiers",
  "LineProcedure",
  "MarginProcedure",
  "NewTransportMeans",
  "OrderLine",
  "OrderLineProcedure",
  "Party",
  "PartyIdentifierKind",
  "PaymentDue",
  "Registry",
  "TaxSummary",
  "TransactionTerms",
  "Transport",
  "ValidationContext",
  "VatClass",
  "VatRateCode",
  "mapPartyIdentityToXml",
  "resolvePartyIdentifier",
  "toFa3XmlValidationMessage",
  "validateFa3XmlWithParser",
  "validateFa3XmlWithValidator",
  "validatePartyIdentifier",
]);

test("FA(3) public runtime API exposes the local TypeScript contract", () => {
  const exportedKeys = Object.keys(fa3);
  const exportedSet = new Set(exportedKeys);
  const missing = REQUIRED_TS_FA3_SYMBOLS.filter((name) => !exportedSet.has(name));
  assert.deepEqual(missing, []);

  const unexpected = exportedKeys.filter((name) => !ACCEPTED_TS_FA3_SYMBOLS.has(name));
  assert.deepEqual(unexpected, []);
});
